# Generated by Django 3.0.8 on 2020-07-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
    ]
