# Generated by Django 3.0.8 on 2020-07-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ManyToManyField(to='games.DEVELOPER'),
        ),
    ]
