# Generated by Django 3.0.8 on 2020-07-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='about',
        ),
        migrations.AlterField(
            model_name='game',
            name='Age_rating',
            field=models.CharField(choices=[('EVERYONE', 'همه کس'), ('EVERYONE10PLUS', 'همه کس +10'), ('TEEN', 'نوجوان'), ('MATURE17PLUS', 'بالغ +17'), ('ADULTSONLY', 'بزرگ سالان'), ('RATINGPENDING', 'در انتظار')], default='RATINGPENDING', max_length=45),
        ),
    ]
