# Generated by Django 3.0.8 on 2020-07-13 06:48

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200713_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='logo',
            field=models.FileField(upload_to=games.models.developers_path),
        ),
    ]
