# Generated by Django 3.0.8 on 2020-07-13 07:05

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200713_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='logo',
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.FileField(upload_to=games.models.publisher_path),
        ),
    ]
